import {
  Info,
  GraduationCap,
  BookA,
  Microscope,
  UsersRound,
  LibraryBig,
  School,
} from "lucide-react";

export const navLinks = [
  {
    id: 0,
    title: "about us",
    icon: Info,
    sublinks: [
      "overview",
      "management",
      "administration",
      "vision",
      "core values",
      "infrastructure",
    ],
  },
  {
    id: 1,
    title: "academics",
    icon: GraduationCap,
    sublinks: [
      "programmes",
      "ciricullum",
      "council",
      "results",
      "examination",
      "calendar",
    ],
  },
  {
    id: 3,
    title: "admissions",
    icon: BookA,
    sublinks: [
      "information",
      "courses",
      "eligibility",
      "prospects",
      "fee structure",
      "helpline",
    ],
  },
  {
    id: 4,
    title: "departments",
    icon: LibraryBig,
    sublinks: [
      "information",
      "courses",
      "eligibility",
      "prospects",
      "fee structure",
      "helpline",
    ],
  },
  {
    id: 5,
    title: "student support",
    icon: UsersRound,
    sublinks: [
      "information",
      "courses",
      "eligibility",
      "prospects",
      "fee structure",
      "helpline",
    ],
  },
  {
    id: 6,
    title: "Campus",
    icon: School,
    sublinks: [
      "information",
      "courses",
      "eligibility",
      "prospects",
      "fee structure",
      "helpline",
    ],
  },
  {
    id: 7,
    title: "research",
    icon: Microscope,
    sublinks: [
      "information",
      "courses",
      "eligibility",
      "prospects",
      "fee structure",
      "helpline",
    ],
  },
];
