import type { Metadata } from "next";
import Navigation from "@/components/custom/Navigation";
import Footer from "@/components/custom/Footer";

import "./globals.css";
import { primary } from "./fonts";

export const metadata: Metadata = {
  title: "Lyallpur Khalsa College - Jalandhar",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={primary.className}>
        <Navigation />
        {children}
        <Footer />
      </body>
    </html>
  );
}
